<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cecília Figueiredo Alves, Isabela Canuto Paiva, João Marcos Oliveira Neves, Júlia Luíza Costa de Toledo e Rodrigo Anastácio Silva e Pena">
<meta name="dcterms.date" content="2026-06-16">

<title>Trabalho 2 - Inferência Estatística com Abordagem Bayesiana</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Relatorio2_Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/popper.min.js"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Relatorio2_Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Relatorio2_Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Relatorio2_Final_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Relatorio2_Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Relatorio2_Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Relatorio2_Final_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabalho 2 - Inferência Estatística com Abordagem Bayesiana</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Cecília Figueiredo Alves, Isabela Canuto Paiva, João Marcos Oliveira Neves, Júlia Luíza Costa de Toledo e Rodrigo Anastácio Silva e Pena </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>PROBLEMA:</strong> Considere uma amostra <span class="math inline">\(X = (X_1,...,X_N)\)</span> independente e identicamente distribuída da distribuição normal com média µ e variância <span class="math inline">\(σ^2\)</span>, <span class="math inline">\(µ ∈ R\)</span> e <span class="math inline">\(σ^2 ∈ R+\)</span>, ambas desconhecidas. Seu objetivo é estimar <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Para isto utilizará uma distribuição <em>a priori</em> conjugada natural.</p>
<section id="parte-1" class="level1">
<h1>Parte 1:</h1>
<section id="a-geração-da-amostra-escolha-valores-apropriados-para-µσ2.-fixado-estes-parâmetros-gere-uma-amostra-de-tamanho-n-500-da-distribuição-amostral.-armazene-estes-valores-para-análises-posteriores.-faça-uma-apresentação-gráfica-apropriada-da-amostra-gerada.-determine-a-média-variância-curtose-e-assimetria-da-amostra-gerada." class="level4">
<h4 class="anchored" data-anchor-id="a-geração-da-amostra-escolha-valores-apropriados-para-µσ2.-fixado-estes-parâmetros-gere-uma-amostra-de-tamanho-n-500-da-distribuição-amostral.-armazene-estes-valores-para-análises-posteriores.-faça-uma-apresentação-gráfica-apropriada-da-amostra-gerada.-determine-a-média-variância-curtose-e-assimetria-da-amostra-gerada.">a) Geração da amostra: Escolha valores apropriados para <span class="math inline">\((µ,σ^2)\)</span>. Fixado estes parâmetros, gere uma amostra de tamanho n = 500 da distribuição amostral. Armazene estes valores para análises posteriores. Faça uma apresentação gráfica apropriada da amostra gerada. Determine a média, variância, curtose e assimetria da amostra gerada.</h4>
<p><strong>Fixando valores para</strong> <span class="math inline">\(\mu\)</span> <strong>e</strong> <span class="math inline">\(\sigma^2\)</span></p>
<p>No decorrer do Trabalho, foram utilizados os seguintes valores para os parâmetros:</p>
<ul>
<li><p><span class="math inline">\(µ = 10\)</span></p></li>
<li><p><span class="math inline">\(σ^2 = 4\)</span></p></li>
</ul>
<p><strong>Análise gráfica da amostra</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pelo gráfico, nota-se que o formato da curva de densidade da amostra é similar a um sino, indicando que ela é aproximadamente normal. Além disso, também é possível perceber que a distribuição no gráfico está centrada em um valor próximo de 10, o que era de se esperar, dado que a amostra foi gerada de uma Normal com média 10.</p>
<p><strong>Medidas de dispersão e de forma</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Média</th>
<th>Variância</th>
<th>Desvio Padrão</th>
<th>Curtose</th>
<th>Assimetria</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(9.974\)</span></td>
<td><span class="math inline">\(3.595\)</span></td>
<td><span class="math inline">\(1.896\)</span></td>
<td><span class="math inline">\(-0.191\)</span></td>
<td><span class="math inline">\(0.032\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Média-</strong> Próxima do valor real <span class="math inline">\(µ = 10\)</span></p></li>
<li><p><strong>Variância-</strong> Próxima do valor real <span class="math inline">\(σ^2 = 4\)</span></p></li>
<li><p><strong>Desvio Padrão-</strong> Próximo do valor real <span class="math inline">\(σ = \sqrt{σ^2} = \sqrt{4} = 2\)</span></p></li>
<li><p><strong>Curtose-</strong> Próxima de 0, indicando que a curva de densidade da amostra é Mesocúrtica, isto é, ela tem achatamento semelhante ao da curva normal</p></li>
<li><p><strong>Assimetria-</strong> Próxima de 0, indicando que a curva de densidade da amostra é simétrica</p></li>
</ul>
</section>
<section id="b-construção-da-sua-distribuição-a-priori-construa-sua-distribuição-a-priori-conjugada-natural-para-µσ2-tal-que-a-distribuição-para-µ-seja-centrada-no-valor-real-para-a-média-populacional-o-valor-usando-na-geração-dos-dados-e-que-seja-pouco-informativa-isto-é-tenha-uma-variância-grande-e-que-a-distribuição-para-σ2-seja-pouco-informativa.-faça-o-gráfico-das-distribuições-a-priori-para-µ-e-σ2.-calcule-a-média-e-a-variância-a-priori-para-µ-e-σ2." class="level4">
<h4 class="anchored" data-anchor-id="b-construção-da-sua-distribuição-a-priori-construa-sua-distribuição-a-priori-conjugada-natural-para-µσ2-tal-que-a-distribuição-para-µ-seja-centrada-no-valor-real-para-a-média-populacional-o-valor-usando-na-geração-dos-dados-e-que-seja-pouco-informativa-isto-é-tenha-uma-variância-grande-e-que-a-distribuição-para-σ2-seja-pouco-informativa.-faça-o-gráfico-das-distribuições-a-priori-para-µ-e-σ2.-calcule-a-média-e-a-variância-a-priori-para-µ-e-σ2.">b) Construção da sua distribuição a priori: Construa sua distribuição a priori conjugada natural para <span class="math inline">\((µ,σ^2)\)</span> tal que a distribuição para <span class="math inline">\(µ\)</span> seja centrada no valor real para a média populacional (o valor usando na geração dos dados) e que seja pouco informativa (isto é tenha uma variância grande) e que a distribuição para <span class="math inline">\(σ^2\)</span> seja pouco informativa. Faça o gráfico das distribuições a priori para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Calcule a média e a variância a priori para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>.</h4>
<p><strong>Definindo a família distribuições para</strong> <span class="math inline">\((µ, σ^2)\)</span> <strong>conjugada natural</strong></p>
<p>A família de distribuições para <span class="math inline">\((µ, σ^2)\)</span> que é conjugada natural da família <span class="math inline">\(Normal( µ,σ^2)\)</span> com ambos os parâmetros desconhecidos é:</p>
<ul>
<li><p><span class="math inline">\(µ ∼ t - Student(m, V, a, d)\)</span>, tal que <span class="math inline">\(m ∈ R, V &gt; 0, a &gt; 0, d &gt; 0\)</span></p></li>
<li><p><span class="math inline">\(σ^2 ∼ Gama − Inversa(a, d)\)</span>, tal que <span class="math inline">\(a &gt; 0, d &gt; 0\)</span></p></li>
</ul>
<p><strong>Escolhendo valores para os parâmetros das distribuições de</strong> <span class="math inline">\(µ\)</span> <strong>e</strong> <span class="math inline">\(σ^2\)</span></p>
<ul>
<li><p><span class="math inline">\(µ ∼ t - Student(10, 250, 8.128, 4.032)\)</span></p></li>
<li><p><span class="math inline">\(σ^2 ∼ Gama − Inversa(8.128, 4.032)\)</span></p></li>
</ul>
<p>Os parâmetros foram escolhidos de modo que ambas as distribuições a priori estão centradas nos valores de <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span> originais, mas possuem uma variância grande, o que as torna pouco informativas.</p>
<p><strong>Cálculo da Média e Variância de</strong> <span class="math inline">\(µ\)</span></p>
<ul>
<li><p><span class="math inline">\(E(µ) = m = 10\)</span></p></li>
<li><p><span class="math inline">\(V(µ) = \frac{aV}{d − 2} = \frac{8.128*250}{4.032 − 2} = 1000\)</span></p></li>
</ul>
<p><strong>Cálculo da Média e Variância de</strong> <span class="math inline">\(σ^2\)</span></p>
<ul>
<li><p><span class="math inline">\(E(σ^2) = \frac{a}{d − 2} = \frac{8.128}{4.032 − 2} = 4\)</span></p></li>
<li><p><span class="math inline">\(V(σ^2) = \frac{2a^2}{(d − 2)^2(d − 4)} = \frac{2*8.128^2}{(4.032 − 2)^2(4.032 − 4)} = 1000\)</span></p></li>
</ul>
<p><strong>Resumo</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Parâmetro</th>
<th>Distribuição a Priori</th>
<th>Média a Priori</th>
<th>Variância a Priori</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(µ\)</span></td>
<td>t-Student(10, 8.128, 250, 4.032)</td>
<td><span class="math inline">\(10\)</span></td>
<td><span class="math inline">\(1000\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(σ^2\)</span></td>
<td>Gama-Inversa(8.128, 4.032)</td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(1000\)</span></td>
</tr>
</tbody>
</table>
<p>A tabela confirma que as distribuições a priori são não informativas e estão centradas nos valores reais de <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>, isto é:</p>
<ul>
<li><p><span class="math inline">\(E(µ) = E(µ_{real}) = 10\)</span></p></li>
<li><p><span class="math inline">\(E(σ^2) = E(σ^2_{real}) = 4\)</span></p></li>
<li><p><span class="math inline">\(Var(µ) = Var(σ^2) = 1000\)</span></p></li>
</ul>
<p><strong>Análise gráfica da distribuição de</strong> <span class="math inline">\(µ\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico ilustra justamente a alta incerteza da distribuição a priori, haja vista que, mesmo centrada em 10, sua curva atribui uma probabilidade similar tanto para valores próximos, quanto para valores distantes do central.</p>
<p><strong>Análise gráfica da distribuição de</strong> <span class="math inline">\(σ^2\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A priori traz uma massa de probabilidade próxima do valor real, mas ainda trazendo alguma massa de probabilidade para valores mais distantes, mostrando a incerteza atrelada à informação.</p>
</section>
<section id="c-considerando-a-distribuição-a-priori-construída-no-ítem-b-e-os-dados-gerados-no-ítem-a-determine-a-distribuição-a-posteriori-exata-para-µ-e-σ2.-faça-o-gráfico-das-distribuições-a-posteriori-para-µ-e-σ2.-calcule-a-média-a-moda-e-a-variância-a-posteriori-para-µ-e-σ2.-considerando-a-média-a-posteriori-como-o-estimador-dos-parâmetros-µ-e-σ2-determine-o-viés-das-estimativas-obtidas.-considerando-a-moda-a-posteriori-como-o-estimador-dos-parâmetros-µ-e-σ2-determine-o-viés-das-estimativas-obtidas." class="level4">
<h4 class="anchored" data-anchor-id="c-considerando-a-distribuição-a-priori-construída-no-ítem-b-e-os-dados-gerados-no-ítem-a-determine-a-distribuição-a-posteriori-exata-para-µ-e-σ2.-faça-o-gráfico-das-distribuições-a-posteriori-para-µ-e-σ2.-calcule-a-média-a-moda-e-a-variância-a-posteriori-para-µ-e-σ2.-considerando-a-média-a-posteriori-como-o-estimador-dos-parâmetros-µ-e-σ2-determine-o-viés-das-estimativas-obtidas.-considerando-a-moda-a-posteriori-como-o-estimador-dos-parâmetros-µ-e-σ2-determine-o-viés-das-estimativas-obtidas.">c) Considerando a distribuição a priori construída no ítem (b) e os dados gerados no ítem (a), determine a distribuição a posteriori exata para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Faça o gráfico das distribuições a posteriori para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Calcule a média, a moda e a variância a posteriori para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Considerando a média a posteriori como o estimador dos parâmetros <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span> determine o viés das estimativas obtidas. Considerando a moda a posteriori como o estimador dos parâmetros <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span> determine o viés das estimativas obtidas.</h4>
<p>As distribuições a posteriori exatas para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span> são:</p>
<ul>
<li><p><span class="math inline">\(µ|x ∼ t - Student(m^*, V^*, a^*, d^*)\)</span>, tal que <span class="math inline">\(m^* ∈ R, V^* &gt; 0, a^* &gt; 0, d^* &gt; 0\)</span></p></li>
<li><p><span class="math inline">\(σ^2|x ∼ Gama − Inversa(a^*,d^*)\)</span>, tal que <span class="math inline">\(a^* &gt; 0, d^* &gt; 0\)</span></p></li>
</ul>
<p>em que</p>
<ul>
<li><p><span class="math inline">\(a^* = a + \sum_{i_1}^{n} x_i^2 + \frac{m^2}{V} - \frac{(nV\bar{x} + m)^2}{V(nV+ 1)} = 1801.805\)</span></p></li>
<li><p><span class="math inline">\(d^* = d + n = 504.032\)</span></p></li>
<li><p><span class="math inline">\(m^* = \frac{nV\bar{x} + m}{nV+ 1} = 9.974\)</span></p></li>
<li><p><span class="math inline">\(V^* = \frac{V}{nV + 1} = 0.002\)</span></p></li>
</ul>
<p><strong>Cálculo da Média, Moda e Variância de</strong> <span class="math inline">\(µ|x\)</span></p>
<ul>
<li><p><span class="math inline">\(E(µ|x) = m^* = 9.974\)</span></p></li>
<li><p><span class="math inline">\(\text{Moda}(\mu|x) = m^* = 9.974\)</span></p></li>
<li><p><span class="math inline">\(V(µ|x) = \frac{a^*V^*}{d^* − 2} = \frac{1801.805*0.002}{504.032 − 2} = 0.007\)</span></p></li>
</ul>
<p><strong>Cálculo da Média, Moda e Variância de</strong> <span class="math inline">\(σ^2|x\)</span></p>
<ul>
<li><p><span class="math inline">\(E(σ^2|x) = \frac{a^*}{d^* − 2} = \frac{1801.805}{504.032 − 2} = 3.589\)</span></p></li>
<li><p><span class="math inline">\(\text{Moda}(\sigma^2|x) = \frac{a^*}{d^*+2} = \frac{504.032}{1801.805+2}=3.561\)</span></p></li>
<li><p><span class="math inline">\(V(σ^2|x) = \frac{2(a^*)^2}{(d^* − 2)^2(d^* − 4)} = \frac{2*1801.805^2}{(504.032 − 2)^2(504.032 − 4)} = 0.051\)</span></p></li>
</ul>
<p><strong>Resumo</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Parâmetro</th>
<th>Distribuição a Posteriori</th>
<th>Média a Posteriori</th>
<th>Variância a Posteriori</th>
<th>Moda a Posteriori</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(µ\)</span></td>
<td>t-Student(9.974, 1801.805, 0.002, 504.032)</td>
<td><span class="math inline">\(9.974\)</span></td>
<td><span class="math inline">\(0.007\)</span></td>
<td><span class="math inline">\(9.974\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(σ^2\)</span></td>
<td>Gama-Inversa(1801.805, 504.032)</td>
<td><span class="math inline">\(3.589\)</span></td>
<td><span class="math inline">\(0.051\)</span></td>
<td><span class="math inline">\(3.561\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Cálculo do Viés</strong></p>
<p><strong>Média a posteriori como o estimador dos parâmetros</strong></p>
<ul>
<li><p><span class="math inline">\(Viés(\mu) = 9.974 - 10 = -0.026\)</span></p></li>
<li><p><span class="math inline">\(Viés(\sigma^2) = 3.589 - 4 = -0.411\)</span></p></li>
</ul>
<p><strong>Moda a posteriori como o estimador dos parâmetros</strong></p>
<ul>
<li><p><span class="math inline">\(Viés(\mu) = 9.974 - 10 = -0.026\)</span></p></li>
<li><p><span class="math inline">\(Viés(\sigma^2) = 3.561 - 4 = -0.493\)</span></p></li>
</ul>
<p><strong>Resumo</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Parâmetro</th>
<th>Valor Real</th>
<th>Média a Posteriori</th>
<th>Moda a Posteriori</th>
<th>Viés da média como estimador</th>
<th>Viés da moda como estimador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(µ\)</span></td>
<td><span class="math inline">\(10\)</span></td>
<td><span class="math inline">\(9.974\)</span></td>
<td><span class="math inline">\(9.974\)</span></td>
<td><span class="math inline">\(-0.026\)</span></td>
<td><span class="math inline">\(-0.026\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(σ^2\)</span></td>
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(3.589\)</span></td>
<td><span class="math inline">\(3.561\)</span></td>
<td><span class="math inline">\(-0.411\)</span></td>
<td><span class="math inline">\(-0.493\)</span></td>
</tr>
</tbody>
</table>
<p>É possível notar que a média e a moda a posteriori são ótimos estimadores para <span class="math inline">\(\mu\)</span>, dado que seus valores coincidem em 9.974 e ambos apresentam um viés mínimo e próximo a zero, de -0.026. Para o parâmetro <span class="math inline">\(\sigma^2\)</span>, observa-se que ambos os estimadores subestimam o valor real de 4. A média a posteriori se mostra um estimador ligeiramente melhor, visto que seu viés de -0.411 é um pouco menor em valor absoluto quando comparado ao viés da moda a posteriori, que é de -0.493. Embora a diferença entre os estimadores de <span class="math inline">\(\sigma^2\)</span> não seja tão discrepante, o fato de a moda apresentar um viés maior, subestimando mais o valor real, ainda pode ser justificado por ela representar apenas o pico da distribuição. Dessa forma, a moda acaba sendo menos sensível à cauda pesada típica da distribuição gamma-inversa, uma característica que é melhor capturada pela média.</p>
<p><strong>Análise gráfica da distribuição de</strong> <span class="math inline">\(µ|x\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A curva a posteriori está centrada em um valor muito próximo de 10 e atribui uma alta probabilidade para esse valor, assumindo uma incerteza significativamente menor do que a da distribuição a priori.</p>
<p><strong>Análise gráfica da distribuição de</strong> <span class="math inline">\(σ^2|x\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A curva traz a maior parte da sua massa de probabilidade entre 2.5 e 5, onde se encontra o verdadeiro valor do parâmetro, reduzindo a incerteza quando comparada à priori.</p>
</section>
</section>
<section id="parte-2" class="level1">
<h1>Parte 2:</h1>
<p>Considerando a amostra gerada em <strong>(a)</strong> e a distribuição a priori conjugada natural para <span class="math inline">\((µ,σ^2)\)</span> em <strong>(b)</strong></p>
<section id="d-encontre-as-expressões-das-funções-densidades-para-µ-σ2x-e-σ2-µx-isto-é-das-distribuições-condicionais-completas-a-posteriori." class="level4">
<h4 class="anchored" data-anchor-id="d-encontre-as-expressões-das-funções-densidades-para-µ-σ2x-e-σ2-µx-isto-é-das-distribuições-condicionais-completas-a-posteriori.">d) Encontre as expressões das funções densidades para <span class="math inline">\(µ | σ^2,x\)</span> e <span class="math inline">\(σ^2 | µ,x\)</span> (Isto é, das distribuições condicionais completas a posteriori.)</h4>
<p>A densidade a posteriori conjunta é proporcional ao produto da verossimilhança pela priori: <span class="math display">\[p(\mu,\sigma^{2}|x)\propto L(\mu,\sigma^{2}|x)p(\mu|\sigma^{2})p(\sigma^{2})\]</span></p>
<p>De modo que a verossimilhança da amostra Normal é: <span class="math display">\[L(\mu,\sigma^{2}|x)\propto(\sigma^{2})^{-n/2}\exp\left(-\frac{1}{2\sigma^{2}}\sum_{i=1}^{n}(x_{i}-\mu)^{2}\right)\]</span></p>
<ol type="1">
<li><strong>Condicional completa para</strong> <span class="math inline">\(\mu\)</span>: Tratando <span class="math inline">\(\sigma^2\)</span> como uma constante e isolando apenas os termos que dependem de <span class="math inline">\(\mu\)</span> na distribuição conjunta, obtemos o núcleo de uma distribuição Normal. <span class="math display">\[p(\mu|\sigma^{2},x)\sim Normal(m^*,V^*\sigma^{2})\]</span></li>
</ol>
<p>Onde:</p>
<ul>
<li><p><span class="math inline">\(V^*= \frac{V}{nV + 1}\)</span></p></li>
<li><p><span class="math inline">\(m^*=\frac{nV\bar{x} + m}{nV+ 1}\)</span></p></li>
</ul>
<ol start="2" type="1">
<li><strong>Condicional completa para</strong> <span class="math inline">\(\sigma^{2}\)</span><strong>:</strong> Tratando <span class="math inline">\(\mu\)</span> como uma constante e isolando os termos que dependem de <span class="math inline">\(\sigma^{2}\)</span> (e tratando <span class="math inline">\(\mu\)</span> como uma constante conhecida), obtemos o núcleo de uma distribuição Gama Inversa. <span class="math display">\[p(\sigma^{2}|\mu,x)\sim Gama - Inversa(a^*,d^*)\]</span></li>
</ol>
<p>Onde:</p>
<ul>
<li><p><span class="math inline">\(a^* = a + \sum_{i=1}^{n} (x_i - \mu)^2 + \frac{(\mu - m)^2}{V}\)</span></p></li>
<li><p><span class="math inline">\(d^* = d + n + 1\)</span></p></li>
</ul>
</section>
<section id="e-implemente-o-amostrador-de-gibbs-e-obtenha-amostras-das-distribuições-a-posterior-para-µ-e-σ2.-inicie-as-cadeias-de-dois-valores-inciais-distintos-um-bem-próximo-do-valor-real-do-parâmetro-e-outro-bem-longe.-faça-uma-análise-da-convergência-das-cadeias-e-da-autocorrelação.-considere-uma-amostra-com-baixa-correlação-entre-os-valores-gerados-e-compare-a-distribuição-obtida-usando-este-amostrador-e-a-distribuição-analítica-obtida-na-parte-1-compare-os-gráficos-das-distribuições-as-médias-modas-e-variâncias." class="level4">
<h4 class="anchored" data-anchor-id="e-implemente-o-amostrador-de-gibbs-e-obtenha-amostras-das-distribuições-a-posterior-para-µ-e-σ2.-inicie-as-cadeias-de-dois-valores-inciais-distintos-um-bem-próximo-do-valor-real-do-parâmetro-e-outro-bem-longe.-faça-uma-análise-da-convergência-das-cadeias-e-da-autocorrelação.-considere-uma-amostra-com-baixa-correlação-entre-os-valores-gerados-e-compare-a-distribuição-obtida-usando-este-amostrador-e-a-distribuição-analítica-obtida-na-parte-1-compare-os-gráficos-das-distribuições-as-médias-modas-e-variâncias.">e) Implemente o Amostrador de Gibbs e obtenha amostras das distribuições a posterior para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Inicie as cadeias de dois valores inciais distintos, um bem próximo do valor real do parâmetro e outro bem longe. Faça uma análise da convergência das cadeias e da autocorrelação. Considere uma amostra com baixa correlação entre os valores gerados e compare a distribuição obtida usando este amostrador e a distribuição analítica obtida na Parte 1 (Compare os gráficos das distribuições, as médias, modas e variâncias.</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'coda' foi compilado no R versão 4.5.3</code></pre>
</div>
</div>
<section id="estudo-para-mu" class="level5">
<h5 class="anchored" data-anchor-id="estudo-para-mu">Estudo para <span class="math inline">\(\mu\)</span>:</h5>
<p>Visualização das cadeias da amostra gerada da posteriori para <span class="math inline">\(\mu\)</span> incluindo o burn-in:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>É possível visualizar que, por se tratar do amostrador de Gibbs (onde as amostras são retiradas diretamente das distribuições exatas), a cadeia estabiliza de forma quase imediata, muito antes da iteração 500. Utilizando um burn-in de 1000 iterações, assim fica o gráfico da cadeia de <span class="math inline">\(\mu\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fazendo apenas a análise do gráfico das cadeias de <span class="math inline">\(\mu\)</span>, não temos nenhuma evidência de que a cadeia não convergiu. Realizando o teste de Gelman-Rubin para convergência das cadeias, temos que:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimativa Pontual</th>
<th>Limite Superior do Intervalo de Confiança</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Como o gráfico não traz nenhum indício de que as cadeias não convergiram, e o teste de Gelman-Rubin nos deu uma estimativa pontual cravada em 1, nós temos um forte indício de que a cadeia convergiu perfeitamente para a distribuição a posteriori de <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="estudo-para-sigma2" class="level5">
<h5 class="anchored" data-anchor-id="estudo-para-sigma2">Estudo para <span class="math inline">\(\sigma^2\)</span>:</h5>
<p>Visualização das cadeias da amostra gerada da posteriori para <span class="math inline">\(\sigma^2\)</span> incluindo o burn-in:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Novamente, é possível visualizar que a cadeia estabiliza de forma extremamente rápida. Utilizando um burn-in de 1000 iterações, assim fica o gráfico da cadeia de <span class="math inline">\(\sigma^2\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fazendo a análise do gráfico das cadeias de <span class="math inline">\(\sigma^2\)</span>, não temos nenhuma evidência de que a cadeia não convergiu. Realizando o teste de Gelman-Rubin para convergência das cadeias, temos que:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimativa Pontual</th>
<th>Limite Superior do Intervalo de Confiança</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Assim como em <span class="math inline">\(\mu\)</span>, a estimativa pontual de 1 do teste de Gelman-Rubin reforça fortemente a convergência das cadeias para a distribuição a posteriori de <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>Realizando o estudo de autocorrelação das cadeias de</strong> <span class="math inline">\(\mu\)</span> <strong>e</strong> <span class="math inline">\(\sigma^2\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'forecast' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para as cadeias de <span class="math inline">\(\mu\)</span> no Amostrador de Gibbs, a autocorrelação despenca e fica em um nível ideal logo no lag 1.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para as cadeias de <span class="math inline">\(\sigma^2\)</span>, o comportamento é idêntico: a autocorrelação é nula quase que imediatamente.Diferente do algoritmo Metropolis-Hastings, o Amostrador de Gibbs gera amostras diretamente das condicionais exatas, resultando em uma taxa de aceitação de 100% e, consequentemente, correlação mínima entre as iterações. Dessa forma, decidimos utilizar um lag igual a 1 (ou seja, não aplicaremos nenhum thinning descarte, aproveitando toda a amostra gerada após o burn-in).</p>
</section>
<section id="comparação-com-a-distribuição-analítica" class="level5">
<h5 class="anchored" data-anchor-id="comparação-com-a-distribuição-analítica">Comparação com a distribuição analítica</h5>
<p><strong>Para</strong> <span class="math inline">\(\mu\)</span><strong>:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Para</strong> <span class="math inline">\(\sigma^2\)</span><strong>:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tabela comparativa:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parâmetro</th>
<th style="text-align: right;">Média Gibbs</th>
<th style="text-align: right;">Moda Gibbs</th>
<th style="text-align: right;">Variância Gibbs</th>
<th style="text-align: right;">Média Analítica</th>
<th style="text-align: right;">Moda Analítica</th>
<th style="text-align: right;">Variância Analítica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">µ</td>
<td style="text-align: right;">9.9735</td>
<td style="text-align: right;">9.9808</td>
<td style="text-align: right;">0.0073</td>
<td style="text-align: right;">9.974</td>
<td style="text-align: right;">9.9740</td>
<td style="text-align: right;">0.0072</td>
</tr>
<tr class="even">
<td style="text-align: left;">σ²</td>
<td style="text-align: right;">3.5916</td>
<td style="text-align: right;">3.5328</td>
<td style="text-align: right;">0.0521</td>
<td style="text-align: right;">3.589</td>
<td style="text-align: right;">3.5677</td>
<td style="text-align: right;">0.0515</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A comparação entre as distribuições obtidas pelo algoritmo de Gibbs e as distribuições analíticas da Parte 1 indica que este método forneceu uma aproximação excepcional e superior em eficiência. Para <span class="math inline">\(\mu\)</span>, o histograma se ajusta de maneira quase idêntica à curva analítica, sendo que os valores de média e moda simuladas acompanham na risca os teóricos de <span class="math inline">\(9{,}974\)</span>, assim como sua variância. O mesmo rigor de aproximação ocorre para <span class="math inline">\(\sigma^2\)</span>, onde os valores simulados empatam com os resultados obtidos analiticamente. Por reter uma quantidade muito maior de amostras efetivas (Effective Sample Size), já que não precisou de thinning, o erro de simulação de Monte Carlo pelo Gibbs foi irrisório.</p>
</section>
</section>
<section id="f-implemente-o-metropolis-hastings-e-obtenha-amostras-das-distribuições-a-posterior-para-µ-e-σ2.-inicie-as-cadeias-nos-mesmos-valores-inciais-considerados-no-item-anterior.-faça-uma-análise-da-convergência-das-cadeias-e-da-autocorrelação.-considere-uma-amostra-com-baixa-correlação-entre-os-valores-gerados-e-compare-a-distribuição-obtida-usando-este-amostrador-e-a-distribuição-analítica-obtida-na-parte-1-compare-os-gráficos-das-distribuições-as-médias-modas-e-variâncias." class="level4">
<h4 class="anchored" data-anchor-id="f-implemente-o-metropolis-hastings-e-obtenha-amostras-das-distribuições-a-posterior-para-µ-e-σ2.-inicie-as-cadeias-nos-mesmos-valores-inciais-considerados-no-item-anterior.-faça-uma-análise-da-convergência-das-cadeias-e-da-autocorrelação.-considere-uma-amostra-com-baixa-correlação-entre-os-valores-gerados-e-compare-a-distribuição-obtida-usando-este-amostrador-e-a-distribuição-analítica-obtida-na-parte-1-compare-os-gráficos-das-distribuições-as-médias-modas-e-variâncias.">f) Implemente o Metropolis-Hastings e obtenha amostras das distribuições a posterior para <span class="math inline">\(µ\)</span> e <span class="math inline">\(σ^2\)</span>. Inicie as cadeias nos mesmos valores inciais considerados no item anterior. Faça uma análise da convergência das cadeias e da autocorrelação. Considere uma amostra com baixa correlação entre os valores gerados e Compare a distribuição obtida usando este amostrador e a distribuição analítica obtida na Parte 1 (Compare os gráficos das distribuições, as médias, modas e variâncias.</h4>
<section id="estudo-para-mu-1" class="level5">
<h5 class="anchored" data-anchor-id="estudo-para-mu-1">Estudo para <span class="math inline">\(\mu\)</span>:</h5>
<p>Visualização das cadeias da amostra gerada da posteriori para <span class="math inline">\(\mu\)</span> incluindo o burn-in:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>É possível visualizar que a cadeia estabiliza aproximadamente na iteração 500. Utilizando um burn-in de 1000 iterações, assim fica o gráfico da cadeia de <span class="math inline">\(\mu\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fazendo apenas a análise do gráfico das cadeias de <span class="math inline">\(\mu\)</span>, não temos nenhuma evidência de que a cadeia não convergiu. Realizando o teste de Gelman-Rubin para convergência das cadeias, temos que:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimativa Pontual</th>
<th>Limite Superior do Intervalo de Confiança</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.02</td>
<td>1.07</td>
</tr>
</tbody>
</table>
<p><br>
Como o gráfico não trás nenhum indício de que as cadeias não convergiram, e o teste de Gelman-Rubin nos deu uma estimativa pontual de 1.02 (Valores próximos de 1 indicam que a cadeia pode ter convergido), nós temos um forte indício de que a cadeia convergiu para a distribuição à posteriori de <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="estudo-para-sigma2-1" class="level5">
<h5 class="anchored" data-anchor-id="estudo-para-sigma2-1">Estudo para <span class="math inline">\(\sigma^2\)</span>:</h5>
<p>Visualização das cadeias da amostra gerada da posteriori para <span class="math inline">\(\sigma^2\)</span> incluindo o burn-in:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>É possível visualizar que a cadeia estabiliza antes da iteração 500. Utilizando um burn-in de 1000 iterações, assim fica o gráfico da cadeia de <span class="math inline">\(\sigma^2\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fazendo apenas a análise do gráfico das cadeias de <span class="math inline">\(\sigma^2\)</span>, não temos nenhuma evidência de que a cadeia não convergiu. Realizando o teste de Gelman-Rubin para convergência das cadeias, temos que:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimativa pontual</th>
<th>Limite Superior do Intervalo de Confiança</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1.01</td>
</tr>
</tbody>
</table>
<p><br>
Como o gráfico não trás nenhum indício de que as cadeias não convergiram, e o teste de Gelman-Rubin nos deu uma estimativa pontual de 1 (Valores próximos de 1 indicam que a cadeia pode ter convergido), nós temos um forte indício de que a cadeia convergiu para a distribuição à posteriori de <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>Realizando o estudo de autocorrelação das cadeias de</strong> <span class="math inline">\(\mu\)</span> <strong>e</strong> <span class="math inline">\(\sigma^2\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para as cadeias de <span class="math inline">\(\mu\)</span>, a autocorrelação fica em um nível ideal em um lag aproximadamente de 30.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para as cadeias de <span class="math inline">\(\sigma^2\)</span>, a autocorrelação fica em um nível ideal em um lag aproximadamente de 10.</p>
<p>Ao fazer o estudo de autocorrelação para <span class="math inline">\(\sigma^2\)</span> e <span class="math inline">\(\mu\)</span>, decidimos manter um lag de 30, pois é onde a autocorrelação é baixa tanto em <span class="math inline">\(\mu\)</span> quanto em <span class="math inline">\(\sigma^2\)</span>.</p>
</section>
<section id="comparação-com-a-distribuição-analítica-1" class="level5">
<h5 class="anchored" data-anchor-id="comparação-com-a-distribuição-analítica-1">Comparação com a distribuição analítica</h5>
<p><strong>Para</strong> <span class="math inline">\(\mu\)</span><strong>:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Para</strong> <span class="math inline">\(\sigma^2\)</span><strong>:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio2_Final_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Tabela comparativa:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parâmetro</th>
<th style="text-align: right;">Média MH</th>
<th style="text-align: right;">Moda MH</th>
<th style="text-align: right;">Variância MH</th>
<th style="text-align: right;">Média Analítica</th>
<th style="text-align: right;">Moda Analítica</th>
<th style="text-align: right;">Variância Analítica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">µ</td>
<td style="text-align: right;">9.9703</td>
<td style="text-align: right;">9.9807</td>
<td style="text-align: right;">0.0072</td>
<td style="text-align: right;">9.974</td>
<td style="text-align: right;">9.9740</td>
<td style="text-align: right;">0.0072</td>
</tr>
<tr class="even">
<td style="text-align: left;">σ²</td>
<td style="text-align: right;">3.5652</td>
<td style="text-align: right;">3.4587</td>
<td style="text-align: right;">0.0455</td>
<td style="text-align: right;">3.589</td>
<td style="text-align: right;">3.5677</td>
<td style="text-align: right;">0.0515</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A comparação entre as distribuições obtidas pelo algoritmo Metropolis-Hastings e as distribuições analíticas da Parte 1 indica que o algoritmo forneceu uma boa aproximação para ambos os parâmetros. Para <span class="math inline">\(\mu\)</span>, o histograma das amostras geradas pelo MH se ajusta bem à curva t-Student analítica, e as estatísticas são praticamente idênticas: média <span class="math inline">\(9{,}970\)</span> vs <span class="math inline">\(9{,}974\)</span>, moda <span class="math inline">\(9{,}981\)</span> vs <span class="math inline">\(9{,}974\)</span> e variâncias iguais de <span class="math inline">\(0{,}0072\)</span>. Para <span class="math inline">\(\sigma^2\)</span>, os valores também estão próximos: média <span class="math inline">\(3{,}565\)</span> vs <span class="math inline">\(3{,}589\)</span>, moda <span class="math inline">\(3{,}459\)</span> vs <span class="math inline">\(3{,}568\)</span> e variância <span class="math inline">\(0{,}0455\)</span> vs <span class="math inline">\(0{,}0515\)</span>. As pequenas discrepâncias observadas são esperadas e decorrem da natureza estocástica do algoritmo, não indicando falha na aproximação.</p>
</section>
</section>
<section id="g-os-dois-algoritmos-forneceram-boas-aproximações-da-distribuição-a-posteriori-exatas-justifique." class="level4">
<h4 class="anchored" data-anchor-id="g-os-dois-algoritmos-forneceram-boas-aproximações-da-distribuição-a-posteriori-exatas-justifique.">g) Os dois algoritmos forneceram boas aproximações da distribuição a posteriori exatas? Justifique.</h4>
<p>Sim, ambos os algoritmos forneceram excelentes aproximações para as distribuições a posteriori exatas, conseguindo reconstruir com grande precisão as propriedades estocásticas (médias, modas, variâncias e o formato geral das densidades) calculadas analiticamente na Parte 1.</p>
<p>Contudo, embora ambos tenham atingido o objetivo de convergência, eles operam de formas matemáticas distintas, o que se reflete na eficiência de cada um.</p>
</section>
<section id="amostrador-de-gibbs" class="level4">
<h4 class="anchored" data-anchor-id="amostrador-de-gibbs">1. Amostrador de Gibbs</h4>
<p>O Amostrador de Gibbs foi o algoritmo mais eficiente para esse problema.</p>
<p><strong>Justificativa Teórica:</strong> Como a priori utilizada foi a conjugada natural (Normal-Gama Inversa), conhecemos explicitamente as distribuições condicionais completas de <span class="math inline">\(\mu \mid \sigma^2,x\)</span> e <span class="math inline">\(\sigma^2 \mid \mu,x\)</span>. O Gibbs realiza sorteios diretos dessas distribuições em cada iteração, o que implica taxa de aceitação igual a 100%.</p>
<p><strong>Eficiência Prática:</strong> Devido à amostragem direta, a autocorrelação das cadeias caiu praticamente para zero já no <em>lag</em> 1. Dessa forma, não foi necessário aplicar <em>thinning</em>, permitindo o aproveitamento de praticamente todas as iterações após o período de <em>burn-in</em> (cerca de 8000 amostras). Como consequência, as estimativas obtidas foram praticamente idênticas às analíticas, diferindo apenas na terceira ou quarta casa decimal.</p>
</section>
<section id="algoritmo-de-metropolis-hastings" class="level4">
<h4 class="anchored" data-anchor-id="algoritmo-de-metropolis-hastings">2. Algoritmo de Metropolis-Hastings</h4>
<p>O algoritmo de Metropolis-Hastings também produziu excelentes aproximações para a distribuição a posteriori, porém com um custo computacional maior.</p>
<p><strong>Justificativa Teórica:</strong> Diferentemente do Gibbs, o MH não realiza sorteios diretos das distribuições condicionais. Em vez disso, gera propostas por meio de distribuições auxiliares (Normal para <span class="math inline">\(\mu\)</span> e Log-Normal para <span class="math inline">\(\sigma\)</span>) e aceita ou rejeita essas propostas segundo uma probabilidade de aceitação. Como consequência, surgem repetições de estados na cadeia quando propostas são rejeitadas.</p>
<p><strong>Eficiência Prática:</strong> Essa característica gerou níveis mais elevados de autocorrelação. Nos diagnósticos realizados, observou-se que a autocorrelação de <span class="math inline">\(\mu\)</span> somente atingiu níveis adequados por volta do <em>lag</em> 30. Assim, foi necessário aplicar <em>thinning</em>, armazenando apenas uma observação a cada 30 iterações, reduzindo significativamente o tamanho efetivo da amostra (<em>Effective Sample Size – ESS</em>).</p>
<p>As pequenas discrepâncias observadas nas estimativas do MH (por exemplo, variância de <span class="math inline">\(\sigma^2\)</span> igual a <span class="math inline">\(0,0455\)</span> frente ao valor analítico de <span class="math inline">\(0,0515\)</span>) não representam falhas do método. Elas decorrem apenas da variabilidade inerente ao erro de Monte Carlo associado ao menor tamanho efetivo da amostra.</p>
<p>Caso o número total de iterações fosse aumentado (por exemplo, para 100.000 iterações), as estimativas do MH tenderiam a coincidir praticamente com aquelas obtidas pelo Gibbs e com os valores analíticos.</p>
</section>
<section id="comparação-entre-os-métodos" class="level4">
<h4 class="anchored" data-anchor-id="comparação-entre-os-métodos">Comparação entre os métodos</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Critério</th>
<th style="text-align: left;">Amostrador de Gibbs</th>
<th style="text-align: left;">Metropolis-Hastings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Taxa de aceitação</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">Variável</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autocorrelação</td>
<td style="text-align: left;">Muito baixa</td>
<td style="text-align: left;">Relativamente alta</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Necessidade de <em>thinning</em></td>
<td style="text-align: left;">Não</td>
<td style="text-align: left;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tamanho efetivo da amostra</td>
<td style="text-align: left;">Alto</td>
<td style="text-align: left;">Menor</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Precisão das estimativas</td>
<td style="text-align: left;">Quase idêntica à analítica</td>
<td style="text-align: left;">Excelente aproximação</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eficiência computacional</td>
<td style="text-align: left;">Muito alta</td>
<td style="text-align: left;">Moderada</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aplicabilidade</td>
<td style="text-align: left;">Modelos conjugados</td>
<td style="text-align: left;">Modelos conjugados e não conjugados</td>
</tr>
</tbody>
</table>
</section>
<section id="conclusão" class="level4">
<h4 class="anchored" data-anchor-id="conclusão">Conclusão</h4>
<p>Os resultados evidenciam que ambos os algoritmos foram capazes de reproduzir adequadamente as distribuições a posteriori exatas. Entretanto, em modelos normais com prioris conjugadas, o <strong>Amostrador de Gibbs</strong> apresenta desempenho superior devido à possibilidade de amostragem direta das distribuições condicionais completas, produzindo cadeias com baixa autocorrelação e alta eficiência amostral.</p>
<p>Por outro lado, o <strong>Metropolis-Hastings</strong> demonstra sua grande flexibilidade, sendo capaz de aproximar corretamente distribuições a posteriori mesmo quando as condicionais completas não são conhecidas. Por essa razão, permanece como uma ferramenta fundamental para problemas Bayesianos mais gerais e modelos não conjugados.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>